server:
  port: 8080


spring:
  application:
    name: customer

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/customer?useUnicode=true&serverTimezone=UTC
    username: customer
    password: customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

