server:
  port: 8082

spring:
  application:
    name: notification

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/notification?useUnicode=true&serverTimezone=UTC
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key