server:
  port: 8081


spring:
  application:
    name: fraud

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fraud?useUnicode=true&serverTimezone=UTC
    username: fraud
    password: fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-utl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

